# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Vectorized Gompertz Event Simulation (C++)
#'
#' @description
#' Calculates the probability of an event within a one-year time step for a cohort
#' of individuals using a Gompertz proportional hazards model. This function is
#' implemented in C++ via RcppArmadillo for high performance.
#'
#' @param m_ind_traits A numeric matrix of individual characteristics, where each
#'   row represents an individual and columns are variables (e.g., age, biomarkers).
#'   The first column is assumed to be `age`.
#' @param m_coef_ukpds_ind_traits A numeric matrix of the main model
#'   coefficients. Each column corresponds to a different health outcome.
#' @param m_coef_ukpds_other_ind_traits A numeric matrix of ancillary parameters.
#'   It must have two rows: the first for `lambda` (location) and the second for
#'   `rho` (shape). Each column corresponds to a health outcome.
#' @param health_outcome_index An integer specifying the column index (1-based)
#'   for the relevant health outcome in the coefficient matrices.
#'
#' @return
#' An integer matrix of size `n x 1` (where `n` is the number of individuals).
#' A value of 1 indicates the event occurred for that individual in the cycle,
#' and 0 indicates it did not.
#'
#' @export
#'
gompertz_eventC <- function(m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index) {
    .Call(`_microsim_tutorial_gompertz_eventC`, m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index)
}

#' Vectorized Logistic Event Simulation (C++)
#'
#' @description
#' Calculates the probability of a binary event for a cohort of individuals using
#' a logistic regression model. The event occurrence is then simulated based on
#' this probability. This function is implemented in C++ via RcppArmadillo
#' for high performance.
#'
#' @param m_ind_traits A numeric matrix of individual characteristics (predictors),
#'   where each row represents an individual.
#' @param m_coef_ukpds_ind_traits A numeric matrix of the main model
#'   coefficients. Each column corresponds to a different health outcome.
#' @param m_coef_ukpds_other_ind_traits A numeric matrix of ancillary parameters.
#'   The first row must contain the intercept (`lambda`) for each health outcome.
#' @param health_outcome_index An integer specifying the column index (1-based)
#'   for the relevant health outcome in the coefficient matrices.
#'
#' @return
#' An integer matrix of size `n x 1` (where `n` is the number of individuals).
#' A value of 1 indicates the event occurred, and 0 indicates it did not.
#'
#' @export
#'
logistic_eventC <- function(m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index) {
    .Call(`_microsim_tutorial_logistic_eventC`, m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index)
}

#' Vectorized Mortality Simulation (C++) - erroneous version
#'
#' @description
#' Simulates mortality for a cohort of individuals for a single time step.
#' The function determines which of four different mortality risk equations to use
#' based on the individuals' health event status in the current cycle.
#'
#' @note
#' **IMPORTANT**: The current implementation classifies the *entire cohort* of
#' patients into a single event/history category based on the maximum event/history
#' status found across all patients, rather than assessing each patient's status
#' individually. This means all patients in a batch are simulated using the
#' same risk equation.
#'
#' @param m_ind_traits A numeric matrix of patient characteristics for the
#'   **current** cycle. It is used to check for new health events and history.
#'   The function assumes specific column indices for event/history flags.
#' @param m_other_ind_traits A numeric matrix for ancillary data (`lambda`, `rho`,
#'   `death`) for the **current** cycle. Its 'death' column (column 3) will be
#'   overwritten by this function.
#' @param m_other_ind_traits_previous A numeric matrix for ancillary data from the
#'   **previous** cycle. This is used to carry forward the cumulative death status.
#' @param m_coef_ukpds_ind_traits The main model coefficients matrix.
#' @param m_coef_ukpds_other_ind_traits The ancillary model coefficients matrix
#'   (containing `lambda` and `rho` values).
#'
#' @details
#' The function routes the entire cohort to one of four models based on a
#' collective check for new events or any prior history:
#' - **No History, No Event (NHNE):** Calls `gompertz_eventC` with index 22.
#' - **Yes History, No Event (YHNE):** Calls `gompertz_eventC` with index 24.
#' - **No History, Yes Event (NHYE):** Calls `logistic_eventC` with index 23.
#' - **Yes History, Yes Event (YHYE):** Calls `logistic_eventC` with index 25.
#'
#' @return
#' Returns the `m_other_ind_traits` matrix with an updated 'death' column
#' (column 3), reflecting the cumulative mortality status.
#'
#' @export
#'
mortalityCz <- function(m_ind_traits, m_other_ind_traits, m_other_ind_traits_previous, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits) {
    .Call(`_microsim_tutorial_mortalityCz`, m_ind_traits, m_other_ind_traits, m_other_ind_traits_previous, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits)
}

#' Vectorized Mortality Simulation (C++)
#'
#' @description
#' Simulates mortality for a cohort of individuals for a single time step.
#' The function determines which of four different mortality risk equations to use
#' based on the individuals' health event status in the current cycle.
#'
#' @param m_ind_traits A numeric matrix of patient characteristics for the
#'   **current** cycle. It is used to check for new health events and history.
#'   The function assumes specific column indices for event/history flags.
#' @param m_other_ind_traits A numeric matrix for ancillary data (`lambda`, `rho`,
#'   `death`) for the **current** cycle. Its 'death' column (column 3) will be
#'   overwritten by this function.
#' @param m_other_ind_traits_previous A numeric matrix for ancillary data from the
#'   **previous** cycle. This is used to carry forward the cumulative death status.
#' @param m_coef_ukpds_ind_traits The main model coefficients matrix.
#' @param m_coef_ukpds_other_ind_traits The ancillary model coefficients matrix
#'   (containing `lambda` and `rho` values).
#'
#' @details
#' The function routes the entire cohort to one of four models based on a
#' collective check for new events or any prior history:
#' - **No History, No Event (NHNE):** Calls `gompertz_eventC` with index 22.
#' - **Yes History, No Event (YHNE):** Calls `gompertz_eventC` with index 24.
#' - **No History, Yes Event (NHYE):** Calls `logistic_eventC` with index 23.
#' - **Yes History, Yes Event (YHYE):** Calls `logistic_eventC` with index 25.
#'
#' @return
#' Returns the `m_other_ind_traits` matrix with an updated 'death' column
#' (column 3), reflecting the cumulative mortality status.
#'
#' @export
#'
mortalityC <- function(m_ind_traits, m_other_ind_traits, m_other_ind_traits_previous, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits) {
    .Call(`_microsim_tutorial_mortalityC`, m_ind_traits, m_other_ind_traits, m_other_ind_traits_previous, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits)
}

#' Vectorized Biomarker and Lag Variable Update (C++)
#'
#' @description
#' Updates the biomarker values for a cohort of individuals for a single time
#' step. This function performs three main tasks in sequence:
#' 1. Updates lag variables (e.g., `a1c_lag`) with the current biomarker values.
#' 2. Predicts new values for a set of 8 core biomarkers using a linear model.
#' 3. Computes several transformations based on these new biomarker values (e.g.,
#'    `sbp_real` to `sbp`, creating BMI categories).
#'
#' @details
#' **CRITICAL:** This function is highly optimized and operates on the assumption
#' of a fixed matrix structure. It uses hardcoded column indices to read,
#' update, and transform values. The input matrix `m_ind_traits` **must**
#' conform to the specific column order that the model expects. Modifying the
#' input matrix structure without updating the internal indices in this function
#' will lead to incorrect calculations.
#'
#' @param m_ind_traits A numeric matrix of patient characteristics. This matrix
#'   serves as both input (containing values from the previous cycle) and output
#'   (it is modified in-place with updated values for the current cycle).
#' @param m_coef_ukpds_ind_traits A matrix of the main model coefficients. The
#'   function will use the first 8 columns for its predictions.
#' @param m_coef_ukpds_other_ind_traits A matrix of ancillary parameters. The
#'   function will use the first row of the first 8 columns as the `lambda`
#'   (intercept) values.
#'
#' @return
#' The updated `m_ind_traits` matrix with new values for biomarkers, lag
#' variables, and transformed variables for the current simulation cycle.
#'
update_biomarkersC <- function(m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits) {
    .Call(`_microsim_tutorial_update_biomarkersC`, m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits)
}

#' Vectorized Health Event Simulation with Randomization (C++)
#'
#' @description
#' Simulates the occurrence of a set of new health events for a cohort of
#' individuals over a single time step.
#'
#' This function is a core part of the simulation engine and performs three
#' key operations:
#' 1. Updates the health history status for each patient.
#' 2. Processes the list of possible health events in a **random order** to
#'    prevent any bias from a fixed sequence.
#' 3. Simulates each event using the appropriate risk engine (`weibull_eventC` or
#'    `logistic_eventC`), applying special logic for complex events.
#'
#' @details
#' This function uses the column names from the input matrices to find the
#' correct data, making it more robust than functions that rely on hardcoded
#' numeric indices.
#'
#' The following events have special conditional logic:
#' - **`amp`**: First amputation risk depends on ulcer history. Second amputation
#'   risk depends on first amputation history.
#' - **`mi`**: First MI risk is different for males and females. Second MI risk
#'   is different from the first.
#' - **`stroke`**: Second stroke risk is different from the first.
#' - **`ulcer`**: Uses a logistic model instead of a Weibull model.
#'
#' For all events, a new event can only occur if the patient does not have a
#' pre-existing history of that same event.
#'
#' @param m_ind_traits A numeric matrix with named columns containing patient
#'   characteristics. It must include columns for event status (e.g., `"mi_event"`)
#'   and event history (e.g., `"mi_hist"`) for all simulated events.
#' @param m_coef_ukpds_ind_traits A numeric matrix of the main model coefficients,
#'   with named columns corresponding to the risk equations (e.g., `"mi1_male"`).
#' @param m_coef_ukpds_other_ind_traits A numeric matrix of ancillary parameters
#'   (`lambda`, `rho`) with corresponding named columns.
#'
#' @return
#' A `NumericMatrix` with the same dimensions and dimnames as the input
#' `m_ind_traits`, but with updated values in the `_event` and `_hist` columns
#' reflecting the outcomes of the current simulation cycle.
#'
#' @export
#'
update_health_eventsC <- function(m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits) {
    .Call(`_microsim_tutorial_update_health_eventsC`, m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits)
}

#' Vectorized Weibull Event Simulation (C++)
#'
#' @description
#' Calculates the probability of an event within a one-year time step for a cohort
#' of individuals using a Weibull proportional hazards model. Event occurrence is
#' then simulated based on this probability. This function is implemented in C++
#' via RcppArmadillo for high performance.
#'
#' @param m_ind_traits A numeric matrix of individual characteristics. Each row
#'   represents an individual. **CRITICAL:** The 6th column (index 5) of this
#'   matrix must be the diabetes duration (`diab_dur`).
#' @param m_coef_ukpds_ind_traits A numeric matrix of the main model
#'   coefficients. Each column corresponds to a different health outcome.
#' @param m_coef_ukpds_other_ind_traits A numeric matrix of ancillary parameters.
#'   It must have two rows: the first for `lambda` (location) and the second for
#'   `rho` (shape). Each column corresponds to a health outcome.
#' @param health_outcome_index An integer specifying the column index (1-based)
#'   for the relevant health outcome in the coefficient matrices.
#'
#' @return
#' An integer matrix of size `n x 1` (where `n` is the number of individuals).
#' A value of 1 indicates the event occurred for that individual in the cycle,
#' and 0 indicates it did not.
#'
#' @export
#'
weibull_eventC <- function(m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index) {
    .Call(`_microsim_tutorial_weibull_eventC`, m_ind_traits, m_coef_ukpds_ind_traits, m_coef_ukpds_other_ind_traits, health_outcome_index)
}

